In [1]:
# Importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### **Question 1**
What's the version of Pandas that you installed?

In [2]:
pd.__version__

'2.0.3'

### **Question 2**
How many columns are in the dataset?

In [3]:
df = pd.read_csv('housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
# Number of columns
len(df.columns)

10

### **Question 3**
Which columns in the dataset have missing values?

In [5]:
# Name of clumns which have null values
df.columns[df.isnull().any()]

Index(['total_bedrooms'], dtype='object')

In [6]:
# Number of null values columns-wise
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### **Question 4**
How many unique values does the `ocean_proximity` column have?

In [7]:
# Number of unique values
len(df['ocean_proximity'].unique())

5

### **Question 5**
What's the average value of the` median_house_valu`e for the houses located near the bay?

In [8]:
mask = df['ocean_proximity'] == 'NEAR BAY'
df[mask].median_house_value.mean()

259212.31179039303

### **Question 6**
1. 
Calculate the average of total_bedrooms column in the dataset  
2. 
Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous ste  
3. .
Now, calculate the average of total_bedrooms aga  
4. n.
Has it chan  ged?

In [9]:
# 1. Average calculation of total_bedrooms
df['total_bedrooms'].mean()

537.8705525375618

In [10]:
# 2. Fill the null value from mean
df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].mean())

In [11]:
# Can calculating the mean
df['total_bedrooms'].mean()

537.8705525375617

### **Question 7**
1. Select all the options located on islands.  
2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.  
3. Get the underlying NumPy array. Let's call it `X`.  
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.  
5. Compute the inverse of `XTX`.  
6. Create an array `y` with values `[950, 1300, 800, 1000, 1300]`.  
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.  
8. What's the value of the last element of `w`?  

In [12]:
mask = df['ocean_proximity'] == 'ISLAND'
df_island = df[mask]

In [18]:
x_columns = ['housing_median_age', 'total_rooms', 'total_bedrooms']
X = df_island[x_columns].values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [19]:
# Matrix multiplication
XTX = np.matmul(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [15]:
# Calculating the inverse of matix XTX
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [16]:
# Creating array y
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [17]:
w = np.dot(np.dot(XTX_inverse, X.T), y)
w

array([23.12330961, -1.48124183,  5.69922946])